// eslint-disable-next-line import/prefer-default-export
export const encoding = {
  lowerChar: 'a',
  upperChar: 'b',
  A: 'aaaaa',
  B: 'aaaab',
  C: 'aaaba',
  D: 'aaabb',
  E: 'aabaa',
  F: 'aabab',
  G: 'aabba',
  H: 'aabbb',
  I: 'abaaa',
  J: 'abaab',
  K: 'ababa',
  L: 'ababb',
  M: 'abbaa',
  N: 'abbab',
  O: 'abbba',
  P: 'abbbb',
  Q: 'baaaa',
  R: 'baaab',
  S: 'baaba',
  T: 'baabb',
  U: 'babaa',
  V: 'babab',
  W: 'babba',
  X: 'babbb',
  Y: 'bbaaa',
  Z: 'bbaab',
};
